version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.7.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - deps-{{ checksum "package.json" }}
      - run:
          name: installing packages
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: deps-{{ checksum "package.json" }}
      - run:
          name: linting javascript files
          command: npm run eslint
      - run:
          name: testing javascript files
          command: npm run mocha
      - run:
          name: uploading coverage reports
          command: npm run codecov
