version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.7.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Installing Packages
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Linting Javascript files
          command: npm run eslint
      - run:
          name: Testing Javascript files
          command: npm run mocha
